spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/paranoia_zk/config-repo-demo.git
        default-application-name: config-server

server.port: 1201

#如果我们的Git仓库需要权限访问，那么可以通过配置下面的两个属性来实现；
#spring.cloud.config.server.git.username：访问Git仓库的用户名
#spring.cloud.config.server.git.password：访问Git仓库的用户密码